services:
  postgres:
    image: postgres:15
    container_name: auth-postgres-camunda
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: authdbdashy
      POSTGRES_USER: authdbdashy
      POSTGRES_PASSWORD: authdbdashy
    volumes:
      - postgres_data_camunda:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak:
    container_name: keycloak.openid-provider
    image: quay.io/keycloak/keycloak:26.2.4
    command:
      - start-dev
      - --import-realm
    ports:
      - 8087:8080
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: root
      KC_HTTP_PORT: 8087
      KC_HOSTNAME_URL: http://localhost:8087
      KC_HOSTNAME_ADMIN_URL: http://localhost:8087
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data_camunda:
