services:
  postgres:
    image: postgres:15
    container_name: auth-postgres-camunda
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: authdbdashy
      POSTGRES_USER: authdbdashy
      POSTGRES_PASSWORD: authdbdashy
    volumes:
      - postgres_data_camunda:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_camunda:
